app_name: sql-window-functions-sample
version: 1
connections:
  - config : !LocalStorage
      details:
        path: ../data
      tables:
        - !Table
          name: trips
          config: !Parquet
            path: trips
            extension: .parquet
    name: ny_taxi

sources:
  - name: trips
    table_name: trips
    connection: ny_taxi

sql: |

  SELECT t.PULocationID as location, t.pickup_datetime, t.window_start as start, t.window_end AS end
  INTO table1
  FROM TUMBLE(trips, pickup_datetime, '5 MINUTES') t;

  SELECT t.PULocationID as location, t.pickup_datetime, t.window_start as start, t.window_end AS end
  INTO table2
  FROM HOP(trips, pickup_datetime, '1 MINUTE', '2 MINUTES') t;

endpoints:
  - name: tumble
    path: /tumble
    table_name: table1

  - name: hop
    path: /hop
    table_name: table2

cache_max_map_size: 2147483648
